---
# Global configuration
- name: apply common configuration to all nodes
  hosts: vagrant-local

  roles:
    - { role: common, tags: 'common'}
    - { role: matlab, tags: 'matlab'}
    - { role: docker, tags: 'docker'}