---
  - name: Copy needed Perl files to server
    copy:
       src=  {{ perl_download_dir }}/{{ item }}
       dest= /tmp/{{ item }}
    with_items:  '{{ perl_modules }}'

  - name: Copy needed Dim file to server
    copy:
       src=  {{ perl_download_dir }}/{{ dim_package }}
       dest= /tmp/{{ dim_package }}


  - name: Install packages on server.
    become: yes
    yum:
       name=/tmp/{{ item }}
       state=present
    with_items: '{{ perl_modules }}'

  - name: Install Dim package on server.
    become: yes
    yum:
       name={{ dim_package }}
       state=present
 

#  - name: make sure dim is started on boot
#    become: yes
#    service:  name=httpd
#              state=started
#              enabled=yes
#    tags:
#      - service

#    become: yes
#    service:  name=httpd
#              state=started
#              enabled=yes
#    tags:
#      - service
