---
  - name: Copy needed files to server
    copy:
       src: /tmp/{{ item }}
       dest: /tmp/{{ item }}
    with_items:
      - perl-Array-Utils-0.5-1.el7.centos.noarch.rpm
      - perl-Data-Traverse-0.03-1.el7.centos.noarch.rpm
      - perl-DateTime-Cron-Simple-0.2-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Duration-1.04-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Duration-XSD-0.01-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Strptime-1.56-1.el7.centos.noarch.rpm
      - perl-Getopt-ArgvFile-1.11-1.el7.centos.noarch.rpm
      - perl-Getopt-Lucid-1.05-1.el7.centos.noarch.rpm
      - perl-Mojolicious-5.17-1.el7.centos.noarch.rpm
      - perl-PAR-1.007-1.el7.centos.noarch.rpm
      - perl-Parallel-ForkManager-1.16-1.el7.centos.noarch.rpm
      - perl-Pod-Markdown-2.002-1.el7.centos.noarch.rpm
      - perl-Schedule-Cron-1.01-1.el7.centos.noarch.rpm
      - perl-XML-LibXML-Iterator-1.04-1.el7.centos.noarch.rpm
      - perl-XML-LibXML-Simple-0.94-1.el7.centos.noarch.rpm
      - perl-XML-NodeFilter-0.01-1.el7.centos.noarch.rpm
      - dim-688-3.noarch.rpm 

  - name: Install packages on server.
    become: yes
    yum:
       name: /tmp/{{ item }}
       state: present
    with_items:
      - perl-Array-Utils-0.5-1.el7.centos.noarch.rpm
      - perl-Data-Traverse-0.03-1.el7.centos.noarch.rpm
      - perl-DateTime-Cron-Simple-0.2-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Duration-1.04-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Duration-XSD-0.01-1.el7.centos.noarch.rpm
      - perl-DateTime-Format-Strptime-1.56-1.el7.centos.noarch.rpm
      - perl-Getopt-ArgvFile-1.11-1.el7.centos.noarch.rpm
      - perl-Getopt-Lucid-1.05-1.el7.centos.noarch.rpm
      - perl-Mojolicious-5.17-1.el7.centos.noarch.rpm
      - perl-PAR-1.007-1.el7.centos.noarch.rpm
      - perl-Parallel-ForkManager-1.16-1.el7.centos.noarch.rpm
      - perl-Pod-Markdown-2.002-1.el7.centos.noarch.rpm
      - perl-Schedule-Cron-1.01-1.el7.centos.noarch.rpm
      - perl-XML-LibXML-Iterator-1.04-1.el7.centos.noarch.rpm
      - perl-XML-LibXML-Simple-0.94-1.el7.centos.noarch.rpm
      - perl-XML-NodeFilter-0.01-1.el7.centos.noarch.rpm

  - name: Install Dim package on server.
    become: yes
    yum:
       name: dim-688-3.noarch.rpm 
       state: present
 

#  - name: make sure dim is started on boot
#    become: yes
#    service:  name=httpd
#              state=started
#              enabled=yes
#    tags:
#      - service

#    become: yes
#    service:  name=httpd
#              state=started
#              enabled=yes
#    tags:
#      - service
